
tasks:
  - init:  npm install && npm run build
    command: |
      npm run dev


ports:
  - port: 3000
    onOpen: open-browser

    
vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
